try {
    //...
} catch(IOException e) {
    //...
} finally {
    //...
}